Feature/exposed webview
FolioReader/FolioReaderKit pull request #155
Opened 2016-09-21 16:28 UTC by tschob

This PR:
- refactors the `UIWebView` extension to the subclass `FolioReaderWebView`
- Provides a way to let extneral code run java script in a `FolioReaderPage`

2016-09-22 02:38 UTC, hebertialmeida commented on Source/FolioReaderPage.swift
> +            (webView as? FolioReaderWebView)?.isColors = false
Lets reduce the `(webView as? FolioReaderWebView)` cast, we can just cast with guard on beginning of the function.

```swift
guard let webView = webView as? FolioReaderWebView else { return }
```

Then just use `webView` as previously.

2016-09-22 02:39 UTC, hebertialmeida commented on Source/FolioReaderPage.swift
> +            (webView as? FolioReaderWebView)?.setMenuVisible(true, andRect: rect)
Same for casting here and so on...

2016-09-22 02:41 UTC, hebertialmeida requested changes
Why do you think is better to subclass the `UIWebView` instead of a extension, as it is not public to override?

2016-09-22 06:54 UTC, tschob commented
I think it's better to use a subclass instead of an extension because:
- The added logic is only needed in one place and it only contains logic which is needed for the reader and useless for other use cases. With this needs it should normally be a subclass and not an extension.
- The extension effects all `UIWebView` instances in an app which uses the Folio Reader. If Folio Readers `UIMenuController` isn't overridden it's possible to select text in a app owned `UIWebView` instance and choose eg. "Highlight" (as the `UIWebView` extension says it can perform this action).
- Folio Readers `UIWebView` is less customisable as extension as everything which is added will effect all `UIWebView` instances in an app. So only things which don't break other `UIWebView` instances can be added. The old implementation breaks other instances.

2016-09-22 06:55 UTC, tschob commented on Source/FolioReaderPage.swift
> +            (webView as? FolioReaderWebView)?.isColors = false
Yes this seems to be the better approach, I'll adjust it.

2016-09-23 01:25 UTC, hebertialmeida approved these changes

2016-09-23 01:25 UTC, merged