error delegate method
FolioReader/FolioReaderKit pull request #255
Opened 2017-08-06 07:52 UTC by holleB

I needed to react to loading errors in the presenting view controller, so I added some methods.

2017-08-08 20:39 UTC, hebertialmeida requested changes

2017-08-08 20:39 UTC, hebertialmeida commented on Source/FolioReaderContainer.swift
> +            title: "Error",
Could you add the title to the localized config? https://github.com/FolioReader/FolioReaderKit/blob/master/Source/FolioReaderConfig.swift#L203

2017-08-08 20:39 UTC, hebertialmeida commented on Source/FolioReaderContainer.swift
> +        let action = UIAlertAction(title: "OK", style: UIAlertActionStyle.cancel) { [weak self]
Same here.

2017-08-10 05:47 UTC, holleB commented
Will do so at the weekend.

2017-10-03 16:59 UTC, closed without merging