Update RealmSwift from 3.1.1 to 3.11
FolioReader/FolioReaderKit pull request #368
Opened 2018-10-18 13:14 UTC by SaraSaber

Update RealmSwift from 3.1.1 to 3.11.0 to support Xcode 10

2018-10-19 21:35 UTC, revolter commented on Example/Example.xcodeproj/project.pbxproj
> +						DevelopmentTeam = NJ65ARC6W7;
You should discard these changes

2018-10-22 13:33 UTC, hebertialmeida requested changes
Hi @SaraSaber, thank you for your contribution!

Few things, the changes to `DEVELOPMENT_TEAM`, `DevelopmentTeam` pointed out by @revolter as well `PRODUCT_BUNDLE_IDENTIFIER` are not necessary.

Could you update that?

2018-11-27 08:00 UTC, kdvmgn commented
Are all issues solved? Could you merge this pull request, please?)

2018-11-28 15:35 UTC, hebertialmeida commented
There are many unrelated changes on this PR, I will close it for now as this should be just a podfile change.

2018-11-28 15:35 UTC, closed without merging